apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.volumes.csi.volumeAttributes.secretProviderClass }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: ""      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: {{ .Values.keyvaultName }}
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: {{ .Values.objectName }}
          objectType: secret        # object types: secret, key, or cert
          objectAlias: {{ .Values.aliasname }}
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: {{ .Values.tenantId }}         # The tenant ID of the key vault
