apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{ if .Values.deployment.namespace }}namespace:
    {{ .Values.namespace.name }}
  {{- end }}
  annotations:
  {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
  {{- .Values.service.selector | toYaml | nindent 4 }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}