tenantId: "04c72f56-1848-46a2-8167-8e5d36510cbc"
aliasname: "appsettings.json"
deployment:
  name: "dutyfree-deployment"
  app: "dutyfree"
  nodeSelector: "linux"
  tolerations:
  - key: "superappapi" 
    value: "true"
    effect: "NoSchedule"
    operator: "Equal"
  labels:
    app: "dutyfree"
  selector:
    matchLabels:
      app: "dutyfree"
  podLabels:
    app: "dutyfree"
  maxSurge: 25%
  maxUnavailable: 25%
  replica: 5
  containerPort: 80
  resources:
    requests:
      cpu: "400m"
      memory: "1500Mi"
    limit:
      cpu: "2000m"
      memory: "2500Mi"
  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 5
  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 15
    periodSeconds: 5
service:
  name: "dutyfree-api-service"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  selector:
    app: "dutyfree"
  type: ClusterIP
  port: 80
  targetPort: 80
ext_name:
  name: "dutyfree-api-service-ext"
hpa:
  name: "dutyfree-hpa"
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75
volumeMounts:
  name: "secrets-store01-inline"
  mountPath: "/app/appsettings.json"
  subPath: "appsettings.json"   
volumes:
  name: "secrets-store01-inline"
  csi:
    driver: "secrets-store.csi.k8s.io"
    readOnly: "true"
    volumeAttributes:
      secretProviderClass: "azure-kvname-system-msi-dutyfree" 

keyvaultName: "az-adl-sa-stage-keyvault"
objectName: "adl-sa-stage-dutyfree-env"
source:
 name: "/app/adl-sa-stage-dutyfree-env"
destination:
 name: "/app/appsettings.json" 

 #########
metadata: 
  name: "az-adl-dutyfree-api-ingress"
  namespace: "airport-api"
spec: 
  ingressClassName: "nginx"
  rules: 
    host: "duty-free.uat.adanione.com"
    http:
      paths:
        backend: 
         service:
           name: "dutyfree-api-service"
           port: 
             number: 80
        path: /
        pathType: ImplementationSpecific 
secretName: "uatadanione-tls-cert"